
title: Chansey
email: kimjanbyeol@gmail.com 
description: stargazer

# the subpath of the site
# baseurl:  
url: https://starry99.github.io

permalink: /:year-:month/:title
timezone: Asia/Seoul

favicon: /assets/img/favicon.ico

google_analytics: UA-135755815-2
disqus_shortname: starry99

feed:
  path: atom.xml

user:
  name: Chansey
  pic: /assets/img/chansey.png
  picAlt: "chansey"
  job: do the next right thing

exclude:
  - README.md
  - LICENSE
  - github
  - .jekyll-cache

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: true    

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false